swagger: '2.0'
info:
  title: Gift Aid Service
  version: 1.0.0
basePath: /api
schemes:
  - https
paths:
  /giftaid:
    get:
      summary: Get the amount of gift aid reclaimable for donation amount
      parameters:
        - in: query
          name: amount
          type: number
          required: true
          description: |
            A decimal value with a minimum of 2.00 (£2.00) and maximum of 100000.00 (£100,000.00)
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GiftAidResponse'
  /giftaid/donation:
    post:
      summary: Add a new donation
      parameters:
        - in: body
          name: 'NewDonationRequest'
          schema:
            $ref: '#/definitions/NewDonationRequest'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/NewDonationResponse'
definitions:
  GiftAidResponse:
    type: object
    required:
      - donationAmount
      - giftAidAmount
    properties:
      donationAmount:
        type: number
      giftAidAmount: 
        type: number
  NewDonationRequest:
    type: object
    required:
      - name
      - postCode
      - donationAmount
    properties:
      name:
        type: string
      postCode:
        type: string
      donationAmount: 
        type: number
  NewDonationResponse:
    type: object
    required:
      - donationId
    properties:
      donationId:
        type: string